"""
S2_cbf_maze.py — System-2 (SFCBF Safety Filter) for SCATTERED RECTANGLE BLOCKS

✅ Compatible with scenarios generated by:
  maze/generate_benchmark_scenarios_maze.py  -> benchmark_scenarios_maze.json

✅ Solver is MATCHED to your System-1 DB generation (S1_all_data_maze_sfcbf.py):
  - Same nominal controller: least-squares-to-goal
  - Same CBF constraints (smooth distance + grad)
  - Same QP (OSQP, warm_start)
  - Same early-stop-on-goal behavior
  - Same success definition: success = ok(feasible every step) AND collision_free AND goal_reached

Run:
  python maze/S2_cbf_maze.py \
    --scenarios maze/benchmark_scenarios_maze.json \
    --out maze/S2_cbf_results.json \
    --dt 0.05 --n_steps 800 --margin 0.35 --gamma 2.0
"""

from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

import cvxpy as cp
import numpy as np

Rect = Tuple[float, float, float, float]


# ----------------------------
# Smooth geometry primitives (MATCH S1_all_data_maze_sfcbf.py)
# ----------------------------

def smooth_abs(z: float, eps: float = 1e-6) -> float:
    return float(math.sqrt(z * z + eps))


def smooth_max(z: float, eps: float = 1e-6) -> float:
    # smooth approx of max(z,0): 0.5*(z + sqrt(z^2+eps))
    return float(0.5 * (z + math.sqrt(z * z + eps)))


def dist_outside_rect_and_grad(x: np.ndarray, rect: Rect, eps: float = 1e-6) -> Tuple[float, np.ndarray]:
    """
    Smooth distance outside rectangle, and gradient wrt x.
    Returns d >= 0, grad_d in R^2.
    """
    x = np.asarray(x, dtype=float).reshape(2)
    xmin, ymin, xmax, ymax = map(float, rect)

    cx = 0.5 * (xmin + xmax)
    cy = 0.5 * (ymin + ymax)
    hx = 0.5 * (xmax - xmin)
    hy = 0.5 * (ymax - ymin)

    zx = x[0] - cx
    zy = x[1] - cy

    ax = smooth_abs(zx, eps)
    ay = smooth_abs(zy, eps)

    dx_raw = ax - hx
    dy_raw = ay - hy

    dx = smooth_max(dx_raw, eps)
    dy = smooth_max(dy_raw, eps)

    d = math.sqrt(dx * dx + dy * dy + eps)

    dax_dzx = zx / max(ax, 1e-12)
    day_dzy = zy / max(ay, 1e-12)

    sdx = math.sqrt(dx_raw * dx_raw + eps)
    sdy = math.sqrt(dy_raw * dy_raw + eps)
    ddx_ddxraw = 0.5 * (1.0 + dx_raw / max(sdx, 1e-12))
    ddy_ddyraw = 0.5 * (1.0 + dy_raw / max(sdy, 1e-12))

    dd_ddx = dx / max(d, 1e-12)
    dd_ddy = dy / max(d, 1e-12)

    grad = np.zeros(2, dtype=float)
    grad[0] = dd_ddx * ddx_ddxraw * dax_dzx
    grad[1] = dd_ddy * ddy_ddyraw * day_dzy
    return float(d), grad


# ----------------------------
# Nominal controller (MATCH S1_all_data_maze_sfcbf.py)
# ----------------------------

def u_nominal(x: np.ndarray, goal: np.ndarray, A: np.ndarray, B: np.ndarray, u_max: float) -> np.ndarray:
    """
    Least-squares nominal:
      choose u to roughly make xdot point to goal:
        v = -(x-goal), solve B u ≈ v - A x
    """
    x = np.asarray(x, dtype=float).reshape(2)
    goal = np.asarray(goal, dtype=float).reshape(2)
    A = np.asarray(A, dtype=float).reshape(2, 2)
    B = np.asarray(B, dtype=float)

    v = -(x - goal)
    rhs = v - A @ x
    u, *_ = np.linalg.lstsq(B, rhs, rcond=None)
    u = np.clip(u, -float(u_max), float(u_max))
    return u.reshape(-1)


# ----------------------------
# CBF-QP Safety filter (MATCH S1_all_data_maze_sfcbf.py)
# ----------------------------

def cbf_filter_qp(
    x: np.ndarray,
    u_nom: np.ndarray,
    A: np.ndarray,
    B: np.ndarray,
    rects: List[Rect],
    *,
    margin: float,
    gamma: float,
    u_max: float,
    eps_geom: float = 1e-6,
) -> Tuple[np.ndarray, bool]:
    """
    Solve:
      minimize ||u - u_nom||^2
      s.t. u in [-u_max, u_max]
           grad_d^T (A x + B u) >= -gamma * (d - margin)
    Returns (u_star, feasible_flag).
    On infeasible/solver failure: returns (u_nom, False).
    """
    x = np.asarray(x, dtype=float).reshape(2)
    u_nom = np.asarray(u_nom, dtype=float).reshape(-1)
    A = np.asarray(A, dtype=float).reshape(2, 2)
    B = np.asarray(B, dtype=float)
    m = int(B.shape[1])

    u = cp.Variable(m)
    obj = cp.Minimize(cp.sum_squares(u - u_nom))
    cons = [u <= float(u_max), u >= -float(u_max)]

    Ax = A @ x
    for rect in rects:
        d, grad_d = dist_outside_rect_and_grad(x, rect, eps=eps_geom)
        h = float(d - margin)
        cons.append(grad_d @ (Ax + B @ u) >= -float(gamma) * h)

    prob = cp.Problem(obj, cons)
    try:
        prob.solve(solver=cp.OSQP, warm_start=True, verbose=False)
        if prob.status not in (cp.OPTIMAL, cp.OPTIMAL_INACCURATE):
            return u_nom.copy(), False
        return np.array(u.value).reshape(m), True
    except Exception:
        return u_nom.copy(), False


# ----------------------------
# Metrics (MATCH S1_all_data_maze_sfcbf.py)
# ----------------------------

def collision_free_rectangles(states: np.ndarray, rects: List[Rect], margin: float = 0.0) -> bool:
    xs = np.asarray(states[:, 0], dtype=float)
    ys = np.asarray(states[:, 1], dtype=float)
    m = float(margin)
    for (xmin, ymin, xmax, ymax) in rects:
        if np.any((xs >= xmin - m) & (xs <= xmax + m) & (ys >= ymin - m) & (ys <= ymax + m)):
            return False
    return True


def goal_reached(states: np.ndarray, goal: Tuple[float, float], tol: float = 0.6) -> bool:
    dx = float(states[-1, 0]) - float(goal[0])
    dy = float(states[-1, 1]) - float(goal[1])
    return (dx * dx + dy * dy) <= float(tol) * float(tol)


# ----------------------------
# Simulation (STOP when goal reached) — MATCH S1_all_data_maze_sfcbf.py
# ----------------------------

def simulate_sfcbf(
    A: np.ndarray,
    B: np.ndarray,
    rects: List[Rect],
    start: Tuple[float, float],
    goal: Tuple[float, float],
    *,
    dt: float,
    n_steps: int,
    u_max: float,
    margin: float,
    gamma: float,
    goal_tol: float,
    collision_margin: float,
) -> Dict[str, Any]:
    A = np.asarray(A, dtype=float).reshape(2, 2)
    B = np.asarray(B, dtype=float)
    m = int(B.shape[1])

    x = np.array(start, dtype=float).reshape(2)
    g = np.array(goal, dtype=float).reshape(2)

    X = [x.copy()]
    U: List[np.ndarray] = []

    t0 = time.perf_counter()
    ok = True

    for _ in range(int(n_steps)):
        # early stop if reached
        if float(np.sum((x - g) ** 2)) <= float(goal_tol) ** 2:
            break

        u0 = u_nominal(x, g, A, B, u_max=u_max)
        u1, feas = cbf_filter_qp(x, u0, A, B, rects, margin=margin, gamma=gamma, u_max=u_max)

        if not feas:
            ok = False  # MATCH: mark not-ok, still simulate with returned u (nominal)

        xdot = A @ x + B @ u1
        x = x + float(dt) * xdot

        X.append(x.copy())
        U.append(u1.copy())

    runtime = float(time.perf_counter() - t0)
    Xn = np.array(X, dtype=float)
    Un = np.array(U, dtype=float).reshape(-1, m)

    cf = bool(ok) and collision_free_rectangles(Xn, rects, margin=collision_margin)
    gr = goal_reached(Xn, goal, tol=goal_tol)
    succ = bool(cf and gr)

    return {
        "states": Xn.tolist(),
        "inputs": Un.tolist(),
        "runtime_sec": runtime,
        "success": succ,
        "collision_free": bool(cf),
        "goal_reached": bool(gr),
        "ok_qp_all_steps": bool(ok),
        "T_steps_executed": int(len(Xn) - 1),
    }


# ----------------------------
# CLI — runs on benchmark_scenarios_maze.json from generator
# ----------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenarios", type=str, default="maze/benchmark_scenarios_maze.json")
    ap.add_argument("--out", type=str, default="maze/S2_cbf_results.json")
    ap.add_argument("--dt", type=float, default=0.05)
    ap.add_argument("--n_steps", type=int, default=800)
    ap.add_argument("--u_max", type=float, default=3.0)
    ap.add_argument("--margin", type=float, default=0.35)
    ap.add_argument("--gamma", type=float, default=2.0)
    ap.add_argument("--goal_tol", type=float, default=0.6)
    ap.add_argument("--collision_margin", type=float, default=0.05)
    args = ap.parse_args()

    scenarios = json.loads(Path(args.scenarios).read_text())
    if not isinstance(scenarios, list):
        raise TypeError("Expected scenarios JSON to be a list of scenario dicts.")

    results: List[Dict[str, Any]] = []

    total_t0 = time.perf_counter()
    for k, sc in enumerate(scenarios):
        sid = int(sc.get("scenario_id", k))

        A = sc.get("A_query", sc.get("A"))
        B = sc.get("B_query", sc.get("B"))
        if A is None or B is None:
            raise KeyError(
                f"Scenario {sid} missing A_query/B_query (or A/B). Keys={list(sc.keys())}"
            )

        rects = [tuple(map(float, r)) for r in sc["rectangles"]]

        # generator includes these; if missing, we keep safe defaults
        start = tuple(map(float, sc.get("start", (5.0, 5.0))))
        goal = tuple(map(float, sc.get("goal", (0.0, 0.0))))

        # scenario may override u_max
        u_max = float(sc.get("u_max", args.u_max))

        out = simulate_sfcbf(
            A=np.array(A, dtype=float),
            B=np.array(B, dtype=float),
            rects=rects,
            start=start,
            goal=goal,
            dt=args.dt,
            n_steps=args.n_steps,
            u_max=u_max,
            margin=args.margin,
            gamma=args.gamma,
            goal_tol=args.goal_tol,
            collision_margin=args.collision_margin,
        )

        results.append({"scenario_id": sid, **out})

        if (k + 1) % 10 == 0 or (k + 1) == len(scenarios):
            succ = sum(1 for r in results if r["success"])
            print(f"[S2-SFCBF] {k+1}/{len(scenarios)} done | success={succ} ({100.0*succ/max(1,len(results)):.1f}%)")

    total_rt = float(time.perf_counter() - total_t0)
    Path(args.out).write_text(json.dumps(results, indent=2))
    print("[ok] wrote:", args.out)
    print(f"[summary] N={len(results)} total_wall_time_sec={total_rt:.3f}")

    # quick summary stats
    runtimes = np.array([r["runtime_sec"] for r in results], dtype=float)
    succ_flags = np.array([r["success"] for r in results], dtype=bool)
    print(f"[summary] success_rate={100.0*succ_flags.mean():.1f}% | avg_rt={runtimes.mean():.3f}s | median_rt={np.median(runtimes):.3f}s")


if __name__ == "__main__":
    main()